### PR TITLE
Documentation for using MATLAB and Simulink with Quix

### PR DESCRIPTION
**Pull request by smadurange**
Opening this as a draft until the feature is made available in PROD.

### CODE REVIEW

**Review by tomas-quix — DISMISSED** [review]
Please structure the docs to start with Matlab function and then at the end include Simulink. Matlab is probably more likely to be used and it is easier as well. Also please make sure that screenshots for matlab contains only stuff from steps and not other deployments. Thx

**Comment by srosam** [comment]
Please ensure links to external sites use {target=_blank} e.g. `[blah](blah.com){target=_blank}`

Please also use backticks instead of quotes for probably most of the places where quotes have been used e.g.  
```
Enter "Engine Model" for the project name. Enter the input and output topics names (e.g., "simulink-input" and "simulink-output"), and click "Save as Project."
```

There probably also needs to be a bit more whitespace around things like the images.

Images can also be made smaller with I think {width=300} (check other pages for correct syntax)

**Comment by smadurange** [comment]
@tomas-quix @srosam Made the changes requested. I set the image width to 600, because 300 is too small.

**Comment by smadurange** [comment]
@tbedford @srosam please release this together with https://github.com/quixio/quix-samples/pull/411.

**Review by tbedford — DISMISSED** [review]
This works for me. Tested in dev. I got both the MatLab and Simulink pipelines working.

**Comment by tbedford** [comment]
Added "do not merge" label as we're co-ordinating on updates to Code Samples library.

**Review by tbedford — APPROVED** [review]
Tested on dev. LGTM.

**Review by SteveRosam — APPROVED** [review]
I haven't tested the code but read through it and it looks good to me.

**Pull request merged**
